### ISSUE TITLE
Create Dev Edmonton Operating Budget

### ISSUE THREAD

**Issue by SteveReiter** [devedmonton/devedmonton-org#12]
We need to determine what our expenses will be.

Website cost
Accounting (Software and/or services)
Email services (gmail)?
Business cards?
Stickers/other swag?
etc.

# TODO
* [ ] Decide how we want to cover the cost of operating DevEdmonton (membership fees, portion of funds raised for meetups, direct society sponsorship, other?)
* [ ] Complete DRAFT budget
* [ ] Pass a resolution approving budget

**Comment by MarkBennett** [comment]
I've got a draft of the budget on Drive:

https://docs.google.com/spreadsheets/d/1x7WuQNVFUjPbFiF_mmT2ZH96caYaWyUqGX8hnsLEOQo/edit?usp=sharing

**Comment by abramhindle** [comment]
Q1. What is that 4k from? Did we get a sponsor?
Q2. What is the 30 bucks per month for accounting?

Suggestion: the exec pay membership dues at the very least.
Suggestion: membership dues at 20-30 bucks. 20 is easy because it is our base denomination from bank machines.
Suggestion: that at least 1 executive of the sponsored meetup pay the membership dues.
Suggestion: we don't take money for operation from the meetups for the first year and we warn them that we might lean on them after year 1 for operating expenses.
Suggestion: we make it clear that any fees or costs incurred by supporting a meetup be borne by the meetup.

**Comment by MarkBennett** [comment]
Good comments @abramhindle. See my responses below.

> Q1. What is that 4k from? Did we get a sponsor?

That's money pledged to Exchange.js last year but not collected. We'll probably want to raise a little more this year to cover the overflow in the budget but $500-1000 would be enough. I'll reformat the budget to make income clearer.

> Q2. What is the 30 bucks per month for accounting?

Estyn and I are going to try to use Google Sheets to do our books, but we've been looking at it and are pretty sure we'll need to spring for a more traditional book keeping solution which is around $30/month. I've been trying GnuCash but have found it unstable so far and it doesn't include the book keeping codes that the CRA looks for in financial statements. It's reporting is written in Scheme so we might be able to modify it to work, but I don't have the bandwidth for that myself right now.

Long story short, I wanted to include these fees in case we decide paying for bookkeeping software like Xero or Quicken is needed.

> 
> Suggestion: the exec pay membership dues at the very least.

Sure. This makes sense.

> Suggestion: membership dues at 20-30 bucks. 20 is easy because it is our base denomination from bank machines.

$20 seems like a reasonable amount. If we wanted to cover the funding gap that way we'd need to recruit around 25 members.

> Suggestion: that at least 1 executive of the sponsored meetup pay the membership dues.

Agreed.

> Suggestion: we don't take money for operation from the meetups for the first year and we warn them that we might lean on them after year 1 for operating expenses.

Would we be willing to go into debt to support this? Personally, I'd rather not setup a line-of-credit so I'd want to cover the outstanding budget by increasing fundraising or reducing expenses.

> Suggestion: we make it clear that any fees or costs incurred by supporting a meetup be borne by the meetup.

Also agree.

**Comment by benzittlau** [comment]
I'm behind the idea of the exec paying membership dues as a way to get some basic initial funding for operating costs.

I'd really, really, really, like us to avoid going into debt if at all avoidable.

Re: QuickBooks, there's kind of a hack we *could* use there.  If you signup for a developer account (which is free) you get access to free sandbox accounts.  There would definitely be risk that these are *not* production accounts, so things like your data would definitely be at much higher risk than a real account.

**Comment by MarkBennett** [comment]
> I'd really, really, really, like us to avoid going into debt if at all avoidable.

👍

**Comment by MarkBennett** [comment]
I've updated the budget with the current projections for income and expenses.

There's about a $200 shortfall we'll need to consider and decide how to handle.

https://docs.google.com/spreadsheets/d/1x7WuQNVFUjPbFiF_mmT2ZH96caYaWyUqGX8hnsLEOQo/edit?usp=sharing

As I see it we'll need to sell 10 additional memberships, charge more per membership, reduce our expenses (accounting software), or find another source of funds.

It looks like we might be able to get a subsidizes copy of Quickbooks which could work for our purposes and would drop the $30/month accounting charge. That seems like a good place to start.

https://www.techsoupcanada.ca/en/intuit/product/quickbooks-premier-canadian-edition-2018-1-user-license-includes-nonprofit-edition
