### ISSUE TITLE
Run an unconference

### ISSUE THREAD

**Issue by MarkBennett** [devedmonton/devedmonton-org#21]
# Background

An "unconference" is an event where the talks and sessions are arranged and decided on the day of by the attendees. As Dev Edmonton is just getting started, arranging a full conference might be too ambitious, however we'd really like to start getting experience organizing large events like this. It also seems like it would be a lot of fun!

This would also be a good opportunity to get other meetups and organisations in Edmonton involved with Dev Edmonton.

# Deliverables
* [ ] Setup an RSVP (and possible ticketing system)
* [ ] Host the unconference

# TODO
* [ ] Decide on format
* [ ] Decide on date
* [ ] Put up a website and some simple copy explaining things
* [ ] Do a budget
* [ ] Arrange sponsorship
* [ ] Setup tickets ($20, students free?)
* [ ] Arrange space
* [ ] Arrange food
* [ ] Arrange A/V equipment
* [ ] Create Code of Conduct
* [ ] Share information with attendees
* [ ] Arrange volunteers for day of event

**Comment by MarkBennett** [comment]
So I talked with @seanhealy and it sounds like he's already got a polyglot conference that's basically this underway. I propose we close this issue and focus on supporting and making sure that Polyglot happens.
