### ISSUE TITLE
Complete 2017-18 Year End

### ISSUE THREAD

**Issue by MarkBennett** [devedmonton/devedmonton-org#28]
To do this, we need to:

* [ ] Publish our financials for the board and membership
* [ ] Organize our AGM (#30)
* [ ] Share our financials at the AGM
* [ ] Mail year-end paperwork to Service Alberta (#32)
* [ ] File taxes with the CRA (#31)
* [ ] Change our official address (#29)

In regards to changing our address, my husband Matt let me use his work address temporarily to get everything started, however given it's at a law firm he's worried Service Alberta will think that his firm represents us, which they don't. We need to decide on a new address then pass a resolution to use it. This address will be on the public record and is where we'll get notices from Service Alberta and the CRA so it needs to be somewhere we can receive mail. See #29.

**Comment by MarkBennett** [comment]
Ping @Estyn and @SteveReiter. Are you able to take care of any of these items?

**Comment by Estyn** [comment]
As soon as we can get a bank statement (or the online access) I can put together the financials for the board and the AGM.  I should be able to help with filing with CRA as well, we just need to make sure that it all lines up with what we need to submit with the CRA as well.  

Do we know what the dead lines are for these tasks?  Have we gotten any notifications from CRA yet?
