### ISSUE TITLE
Run 2017-18 AGM

### ISSUE THREAD

**Issue by MarkBennett** [devedmonton/devedmonton-org#30]
We're going to have our 2017-18 Annual General Meeting on January 15th 19:00pm at . All society members are invited to attend. If you'd like to add something to the agenda, please leave a comment below ASAP.

# Agenda
1) Review and accept financials statements
2) Review banking setup
3) Change society address (we can't have it at Matt's office)
5) Sign year-end paperwork
6) Sign year-end taxes
7) Accept new members
8) Review status of outstanding GH issues
9) Plan work needed to support new meetups in September

# TODO
* [X] Find a venue
* [ ] Draft 2017-18 financial statements
* [ ] Complete paperwork to change society address
* [ ] Draft a resolution listing our current board members
* [ ] Complete year-end society registration paperwork
* [ ] Complete CRA paperwork
* [ ] Draft any agreements that new members need to sign
