### ISSUE TITLE
File 2017-18 Taxes with CRA

### ISSUE THREAD

**Issue by MarkBennett** [devedmonton/devedmonton-org#31]
According to the CRA as a non-profit organisation operating only in Canadian dollars in one province, we are able to file taxes using the T2SHORT form. This makes things a lot easier as we only need to file this form along with the required schedules that go along with it.

I don't believe we'll need to complete Schedule 1 (Personal Federal Tax), Schedule 8 (Canada Pension Plan Contributions and Overpayment for 2017) or Schedule 50 (Shareholder Information) but we'll need to watch for these as we complete the T2SHORT.

# TODO
* [ ] Complete [T2SHORT](https://www.canada.ca/en/revenue-agency/services/forms-publications/forms/t2short.html)
* [ ] Complete [T2SCH100 Balance Sheet Information](https://www.canada.ca/en/revenue-agency/services/forms-publications/forms/t2sch100.html)
* [ ] Complete [T2SCH125 Income Statement Information](https://www.canada.ca/en/revenue-agency/services/forms-publications/forms/t2sch125.html)
* [ ] Complete [T2SCH141 Notes Checklist](https://www.canada.ca/en/revenue-agency/services/forms-publications/forms/t2sch141.html)

**Comment by MarkBennett** [comment]
@Estyn I created an issue to track what work we need to do to file taxes with the CRA
