### ISSUE TITLE
Create a meetup sidekick program

### ISSUE THREAD

**Issue by MarkBennett** [devedmonton/devedmonton-org#35]
## OBJECTIVE

Create a program to make new meetup attendees feel welcome by pairing them with welcoming and trustworthy community members

Attendee a meetup as a newcomer or minority can be intimidating. In talking with our attendees and the community at large, we've recognized there's value in a program of safe community members who have training and understanding of the challenges disenfranchised community members face and are willing to make themselves available to guide and support new members until they feel able to do so for themselves. In particular, we'd like to provide on-demand resources at events so that existing community members can publicily and visibly identify themselves as a safe and welcoming person that new attendees can seek out for support. We'd also like to allow new members to connect with an existing pool of these sidekicks or guides in advance so they can arrive knowing that they won't be going alone.

## TODO
* [ ] Decide on a name for the program and the sidekicks/guides
* [ ] Develop any agreement that meetup sidekicks need to agree to (Code of Conduct?)
* [ ] Make a cute mascot
* [ ] Come up with a lanyard / sticker for attendees
* [ ] Develop any agreement that matchmaking sidekicks need to agree to (background check?)
* [ ] Setup a matchmaking process
* [ ] Identify meetups, events, venues looking to participate
* [ ] Order and distribute sidekick packs to all participants

**Comment by MarkBennett** [comment]
To test the viability of this idea out, we soft launched a "Let's Talk" sticker at the last Exchange.js meetup.

The setup was pretty simple. When people arrived they were offered a name tag by the greater. Along with this there was a pile of bright yellow stickers that could be put on your name tag to indicate you were happy to talk to people and answer questions. During the beginning of the meetup we announced the purpose of the yellow dot, and asked anyone with them to raise their hands.

Casual feedback we got was good. We'll try again at the next meetup, and I'll attempt to approach a new attendee to get their thoughts. I'll also post on Slack to see what people think.

(BTW, this message is a test to see if these comments appear in our Slack. 😉)
